{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Trouble Shooting\n",
    "<br>\n",
    "<a href=\"#upload_issues\">I can't upload my code to the Romi / My Romi won't connect.</a>\n",
    "<br>\n",
    "<a href=\"#serial_timing\">The Timing of my Code changes with Serial.print()</a>\n",
    "<br>\n",
    "<a href=\"#switch_case\">Switch case</a>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "\n",
    "<a id=\"upload_issues\"></a>\n",
    "## I can't upload my code to the Romi / My Romi won't connect:\n",
    "\n",
    "\n",
    "The Romi can sometimes lose its ability to connect to your computer.  Follow these steps to fix it.  On rare occasions, this problem can keep re-occuring, but this method can be repeated quickly and easily.\n",
    "\n",
    "\n",
    "### Step1 \n",
    "- Open the Arduino IDE\n",
    "- Open the Blink Example\n",
    "    - Go to File -> Examples -> Basics -> Blink\n",
    "- Check that the board type `Arduino Leonardo` is selected\n",
    "    - Go to Tools -> Board -> Select `Arduino Leonardo` from the list.\n",
    "\n",
    "Paul\n",
    "\n",
    "### Step 2 \n",
    "- Enable `Show verbose output during: upload`\n",
    "    - Go to File -> Preferences\n",
    "    - Check the `upload` tick box, **so that it is ticked**.\n",
    "    \n",
    "<img src=\"https://github.com/paulodowd/EMATM0054_20_21/blob/master/images/verbose_upload.png?raw=true\">\n",
    "\n",
    "### Step 3\n",
    "\n",
    "\n",
    "- Plug in your Romi to your computer via the USB cable.\n",
    "- Your computer might say \"device not recognised\", don't let this trouble you - <a href=\"https://www.youtube.com/watch?v=fhXvGvH2ZCs\">it is just a glorified filing cabinet</a>.\n",
    "- Go to Tools -> Port and make a note of which ports are available.  You may have many or none.\n",
    "\n",
    "### Step 4\n",
    "\n",
    "- Press the reset button twice - **quickly** \n",
    "    - The reset button is circled red in the image below.\n",
    "    - When you do this correctly, **you should see the built in LED fading** (cirlced green on Romi image).\n",
    "    - Note that, thetes LED should **fade** in and out, not blink on and off.\n",
    "    \n",
    "<pre>\n",
    "<table>\n",
    "    <tr><td><img src=\"https://github.com/paulodowd/EMATM0054_20_21/blob/master/images/Romi_TopDown.jpg?raw=true\" width=\"50%\"></td><td><img src=\"https://github.com/paulodowd/EMATM0054_20_21/blob/master/images/reset_fade.gif?raw=true\" ></td></tr>\n",
    "</table>\n",
    "</pre>\n",
    "\n",
    "### Step 5\n",
    "\n",
    "- **Whilst the LED is fading**\n",
    "    - Go to Tools -> Port and select the newest Port which has shown up.\n",
    "    - If there isn't a new port, select the one with the highest value (e.g., COM10)\n",
    "    - Wait for the Fading LED to go out.  \n",
    "    - If you check Tools -> Port again, this new port may have gone.  This is OK.\n",
    "    \n",
    "### Step 6\n",
    "\n",
    "- Click the upload icon to upload the Blink code to your Romi.\n",
    "- Wait for the code to compile. Wait until the Arduino IDE is searching for the port to connect to.  You will see something like the the white text appearing in the image below.\n",
    "- **When you see the Arduino IDE searching for a port, press the reset button twice (quickly) again to get the fading LED**.\n",
    "\n",
    "<img src=\"https://github.com/paulodowd/EMATM0054_20_21/blob/master/images/searching_for_port.png?raw=true\">\n",
    "\n",
    "### Step 7\n",
    "\n",
    "Wait, and you should see text like the below image confirming the correct upload.  If not, try the process again.  Sometimes it can go wrong if you don't successsfully double-press the reset button quickly enough.  If, after a few attempts, you cannot get this to work, contact one of the teaching staff for the unit.\n",
    "\n",
    "<img src=\"https://github.com/paulodowd/EMATM0054_20_21/blob/master/images/success.png?raw=true\">\n",
    "\n",
    "### Step 8\n",
    "\n",
    "You may wish to:\n",
    "- Share this technique with your peers if they need help.\n",
    "- Meditate on the philosophical implications of fatalism / free-will.\n",
    "- Get back to work."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<pre>\n",
    "<br><br><br>\n",
    "</pre>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<a id=\"serial_timing\"></a>\n",
    "# The Timing of my Code changes with Serial.print()\n",
    "\n",
    "There is a known issue with `Serial.print` and `Serial.println` on the Romi.  You may find that your Romi becomes irratic or the timing of its behaviour changes when you unplug the USB cable.  \n",
    "\n",
    "There are two steps required to fix this problem.  \n",
    "\n",
    "## Step 1:\n",
    "\n",
    "Include the following code at the top of your main program (the first tab in the Arduino IDE):\n",
    "\n",
    "\n",
    "<pre>\n",
    "<font color=\"#5e6d03\">#include</font> <font color=\"#434f54\">&lt;</font><font color=\"#000000\">USBCore</font><font color=\"#434f54\">.</font><font color=\"#000000\">h</font><font color=\"#434f54\">&gt;</font> &nbsp;&nbsp;&nbsp;<font color=\"#434f54\">&#47;&#47; To fix serial print behaviour bug.</font>\n",
    "<font color=\"#000000\">u8</font> <font color=\"#000000\">USB_SendSpace</font><font color=\"#000000\">(</font><font color=\"#000000\">u8</font> <font color=\"#000000\">ep</font><font color=\"#000000\">)</font><font color=\"#000000\">;</font>\n",
    "<font color=\"#5e6d03\">#define</font> <font color=\"#000000\">SERIAL_ACTIVE</font> <font color=\"#000000\">(</font><font color=\"#000000\">USB_SendSpace</font><font color=\"#000000\">(</font><font color=\"#000000\">CDC_TX</font><font color=\"#000000\">)</font> <font color=\"#434f54\">&gt;=</font> <font color=\"#000000\">50</font><font color=\"#000000\">)</font>\n",
    "\n",
    "</pre>\n",
    "\n",
    "\n",
    "\n",
    "Note that, if you use `Serial.print` or `Serial.println` within other source files, you may need to include this at the top of those files too.  Try to compile your code without it, and see if there are useful errors.  \n",
    "\n",
    "## Step 2:\n",
    "\n",
    "At every location you use `Serial.print` or `Serial.println`, you should wrap your code in the following way:\n",
    "<pre>\n",
    "<font color=\"#5e6d03\">if</font><font color=\"#000000\">(</font> <font color=\"#000000\">SERIAL_ACTIVE</font> <font color=\"#000000\">)</font> <font color=\"#000000\">{</font>\n",
    "\n",
    " &nbsp;<b><font color=\"#d35400\">Serial</font></b><font color=\"#434f54\">.</font><font color=\"#d35400\">print</font><font color=\"#000000\">(</font><font color=\"#005c5f\">&#34;An example&#34;</font><font color=\"#000000\">)</font><font color=\"#000000\">;</font>\n",
    " &nbsp;<b><font color=\"#d35400\">Serial</font></b><font color=\"#434f54\">.</font><font color=\"#d35400\">println</font><font color=\"#000000\">(</font><font color=\"#005c5f\">&#34; of fixing the serial bug&#34;</font><font color=\"#000000\">)</font><font color=\"#000000\">;</font>\n",
    "<font color=\"#000000\">}</font>\n",
    "\n",
    "</pre>\n",
    "\n",
    "This will allow you to plug in and remove the USB cable without effecting the performance of your Robot.  \n",
    "\n",
    "Note that, you can also use `if( SERIAL_ACTIVE ) { }` to create different behaviours depending on whether your robot is plugged into USB or not.\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
